export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  SOURCE_VERSION_CHANGED: "SOURCE_VERSION_CHANGED",
  BATCH_INVALIDATED: "BATCH_INVALIDATED",
  BATCH_NOT_COMMITTABLE: "BATCH_NOT_COMMITTABLE",
  BASELINE_CONFLICT: "BASELINE_CONFLICT",
  STORAGE_WRITE_STALE: "STORAGE_WRITE_STALE",
  COMPUTATION_IN_PROGRESS: "COMPUTATION_IN_PROGRESS"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
