export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  SOURCE_CHANGED: "SOURCE_CHANGED",
  DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",
  BATCH_NOT_FOUND: "BATCH_NOT_FOUND",
  BATCH_NOT_PENDING: "BATCH_NOT_PENDING",
  PROMOTE_CONFLICT: "PROMOTE_CONFLICT",
  BATCH_COMPUTE_FAILED: "BATCH_COMPUTE_FAILED"
} as const;
